name: Pull Request CI

on:
  pull_request:
    branches:
      - develop

jobs:
  branch_and_commit_validation:
    runs-on: ubuntu-latest
    extends:
      template: .github/workflows/branch_commit_validation.yml

  build:
    needs: branch_and_commit_validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: E2E tests
        run: npm run test:e2e
